### ISSUE TITLE
Verify property of non-existing resource-type or resource-name is always ok

### ISSUE THREAD

**Issue by rchrd** [bats-core/bats-detik#31] opened 2021-07-22 13:20 UTC
When I try to verify a status field of a non-existing pod the test always returns ok, even if the pod does not exist. The same is the case for a resource type that does not exist.

For example the following test case always returns ok:
```
@test "Verify" {
  verify "'.status.test' is '1' for pod named 'xyz'"
  verify "'.status.test' is '1' for abc named 'xyz'"
}
```

The problem seems to be in `detik.bash` in this line
```
result=$(eval $client_with_options get $resource $query | grep $name | tail -n +1)
```
the error code from the client or grep is hidden by the tail command.

Adding `set -o pipefail` seems to solve this issue.

**Comment by vincent-zurczak** [comment] 2021-07-22 13:22
Hi!

It seems like a duplicate of #29.
If so, I have fixed it yesterday. Could you give it a try?

I was planning a tag for the current version.

**Comment by rchrd** [comment] 2021-07-22 13:33
Sorry, I missed that issue. 

Just tested it and that seems to solve the issue I mentioned. 👍

**Comment by vincent-zurczak** [comment] 2021-07-22 13:36
Thank you for the confirmation.
I had not communicated about this fix, so no problem. I am about to tag a new version.

**Closed by vincent-zurczak** 2021-07-22 13:36 UTC
